eajforms/forms/urls.py
from django.conf.urls import url
from eajforms.forms import views as forms_views

urlpatterns = [
    url(r'^form/new/$', forms_views.form_new, name='form_new'),
    url(r'^form/save/$', forms_views.form_save, name='form_save'),
    url(r'^form/list/$', forms_views.form_list, name='form_list'),
    url(r'^form/(?P<pk>\d+)/apply/$', forms_views.form_apply, name='form_apply'),
    url(r'^apply_form/(?P<access_code>\w+)/response/$', forms_views.form_response, name='form_response'),
    url(r'^apply_form/response/save/$', forms_views.form_response_save, name='form_response_save'),
    url(r'^apply_form/list/$', forms_views.apply_form_list, name='apply_form_list'),
    url(r'^apply_form/(?P<access_code>\w+)/result/$', forms_views.apply_form_result, name='apply_form_result'),
]

eajforms/urls.py
from django.conf.urls import include, url
from django.contrib.auth.views import login, logout
from django.contrib import admin
from eajforms.core import views as core_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', core_views.dashboard, name='home'),
    url(r'^accounts/login/$', login, name='login', kwargs={'redirect_authenticated_user': True}),
    url(r'^accounts/logout/$', logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^dashboard/$', core_views.dashboard, name='dashboard'),
    url(r'', include('eajforms.forms.urls')),
    url(r'', include('eajforms.core.urls'))
]

eajforms/forms/models.py
from django.db import models
from eajforms.core.models import Person

# Create your models here.
class Form(models.Model):
    title = models.CharField('Título', max_length=100)
    description = models.TextField('Descrição', max_length=255)
    create_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    
    class Meta:
        verbose_name = "Formulário"
        verbose_name_plural = "Formulários"

    def __str__(self):
        return self.title

class Question(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    form = models.ForeignKey(Form)
    SHORT_TEXT = 1
    LONG_TEXT = 2
    UNIQUE_CHOICE = 3
    MULTIPLE_CHOICE = 4
    ESCALE = 5
    AGREE_DISAGREE = 6
    TYPE_QUESTION_CHOICES = (
        (SHORT_TEXT, "Texto Curto"),
        (LONG_TEXT, "Texto Longo"),
        (UNIQUE_CHOICE, "Escolha Única"),
        (MULTIPLE_CHOICE, "Escolha Múltipla"),
        (ESCALE, "Escala"),
        (AGREE_DISAGREE, "Concordo ou Discordo"),

    )
    type_question = models.PositiveIntegerField(choices = TYPE_QUESTION_CHOICES)
    is_required = models.BooleanField(default=True)
    related_alternative = models.ForeignKey('Alternative', null=True, blank=True, related_name='related_alternative')
    max_size = models.PositiveIntegerField('Tamanho máximo da resposta', null=True)
    max_scale = models.PositiveIntegerField('Escala máxima da resposta', null=True)
    show_yes_no = models.BooleanField('Mostrar Sim ou Não', default=False)
    left_label = models.CharField('Label esquerdo', max_length=50)
    middle_label = models.CharField('Label central', max_length=50)
    right_label = models.CharField('Label direito', max_length=50)

    class Meta:
        verbose_name = "Questão"
        verbose_name_plural = "Questões"

    def __str__(self):
        return self.title

class Alternative(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=255, null=True, blank=True)
    question = models.ForeignKey(Question)

    class Meta:
        verbose_name = "Alternativa"
        verbose_name_plural = "Alternativas"

    def __str__(self):
        return self.title


class Response(models.Model):
    person = models.ForeignKey(Person, null=True)
    create_at = models.DateTimeField(auto_now_add=True)
    apply_form = models.ForeignKey("ApplyForm", default=1)
    
    class Meta:
        verbose_name = "Resposta Central"
        verbose_name_plural = "Respostas Central"

    def __str__(self):
        return str(self.create_at)


class Answer(models.Model):
    response = models.ForeignKey(Response, null=True)
    question = models.ForeignKey(Question)
    text = models.CharField(max_length=255, null=True)
    scale = models.PositiveIntegerField(null=True)
    dont_apply = models.BooleanField('Não se aplica', default=False)
    OPTION_CHOICES = (
        (1, "Concordo/Sim"),
        (2, "Concordo parcialmente/Parcialmente"),
        (3, "Discordo/Não"),

    )
    yes_no = models.PositiveIntegerField(choices = OPTION_CHOICES, null=True, blank=True)

    class Meta:
        verbose_name = "Resposta"
        verbose_name_plural = "Respostas"

    def __str__(self):
        return str(self.question.title) + " - " + str(self.text) + "Null"

class AnswerOption(models.Model):
    question = models.ForeignKey(Question)
    response = models.ForeignKey(Response)
    option_choice = models.ForeignKey(Alternative, null=True, blank=True)

    class Meta:
        verbose_name = "Alternativa selecionada"
        verbose_name_plural = "Alternativa selecionada"

    def __str__(self):
        return self.question.title + " / " + self.option_choice.title


class ApplyForm(models.Model):
    form = models.ForeignKey(Form)
    DOCENTE = 1
    COORDINATOR = 2
    COURSE = 3
    POLE = 4
    TYPE_EVALUATED_CHOICE = (
        (DOCENTE,"Docente"),
        (COORDINATOR,"Coordenador"),
        (COURSE, "Curso"),
        (POLE, "Polo")

    )
    type_evaluated = models.PositiveIntegerField('Tipo de Avaliado',choices=TYPE_EVALUATED_CHOICE)
    login_required = models.BooleanField('Login é obrigatório?', default=False)
    create_at = models.DateTimeField(auto_now_add=True)
    access_code = models.CharField('código de acesso', unique=True, max_length=64)
    OPEN = 1
    CLOSE = 2
    STATUS_FORM_CHOICES = (
        (OPEN, "Aberto"),
        (CLOSE, "Fechado"),
    )
    status = models.PositiveIntegerField(choices = STATUS_FORM_CHOICES, default=1)

    class Meta:
        verbose_name = "Formulário Aplicado"
        verbose_name_plural = "Formulários Aplicados"

    def __str__(self):
        return self.form.title

eajforms/forms/admin.py
from django.contrib import admin
from eajforms.forms.models import *

# Register your models here.

class AlternativeInline(admin.TabularInline):
    model = Alternative

class QuestionAdmin(admin.ModelAdmin):
    inlines = [AlternativeInline]

class QuestionInline(admin.TabularInline):
    model = Question

class FormAdmin(admin.ModelAdmin):
    inlines = [QuestionInline]

admin.site.register(Form, FormAdmin)
admin.site.register(Question, QuestionAdmin)
admin.site.register(Alternative)
admin.site.register(Answer)
admin.site.register(AnswerOption)
admin.site.register(Response)
admin.site.register(ApplyForm)

eajforms/forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    name = 'forms'

eajforms/forms/tests.py
from django.test import TestCase

# Create your tests here.

eajforms/forms/utils.py
import hashlib, string, random, datetime

from eajforms.forms.models import ApplyForm

def generate_hash_key(salt, random_str_size=5):
    random_str = random_key(random_str_size)
    text = random_str + salt
    generate_hash = hashlib.sha224(text.encode('utf-8')).hexdigest()
    
    if ApplyForm.objects.filter(access_code=generate_hash).exists():
        return generate_hash_key(salt, random_str_size)

    return generate_hash

eajforms/forms/views.py
import json
from django.shortcuts import render, redirect, get_object_or_404, resolve_url as r
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, Http404
from .models import Form, Question, Alternative, Answer, AnswerOption, Response, ApplyForm
from eajforms.core.models import CoordinatorPole
from django.db import transaction


def reply_form(request, formid):
    return render(request, 'form/form_reply.html')


def form_new(request):
    return render(request, 'form/form_form.html')


def form_list(request):
    forms = Form.objects.all()
    return render(request, 'form/form_list.html', {"forms":forms})


def apply_form_list(request):
    apply_forms = ApplyForm.objects.all()
    return render(request, 'apply_form/apply_form_list.html', {"apply_forms":apply_forms})


def apply_form_result(request, access_code):
    apply_form = get_object_or_404(ApplyForm, access_code=access_code)

    return render(request, 'apply_form/apply_form_result.html', {"apply_form":apply_form})


def form_apply(request, pk):
    form = get_object_or_404(Form, pk=pk)

    coordinators_pole = CoordinatorPole.objects.filter(status=1)

    return render(request, 'form/form_apply.html', {"form":form, "coordinators_pole":coordinators_pole})


def form_response(request, access_code):
    apply_form = get_object_or_404(ApplyForm, access_code=access_code)
    form = apply_form.form

    return render(request, 'form/form_response.html', {"form":form, "apply_form":apply_form})


#@transaction.atomic
def form_response_save(request):
    form = Form.objects.get(pk=request.POST["form_id"])
    response = Response()
    response.apply_form = get_object_or_404(ApplyForm, access_code=request.POST["apply_form_access_code"])
    response.save()

    for question in form.question_set.all():
        
        if question.type_question == 1:
            answer = Answer()
            answer.question = question
            answer.response = response
            answer.text = request.POST["question_"+str(question.pk)]
            answer.save()
        elif question.type_question == 2:
            answer = Answer()
            answer.question = question
            answer.response = response
            answer.text = request.POST["question_"+str(question.pk)]
            answer.save()
        elif question.type_question == 3:
            option = request.POST["question_"+str(question.pk)]
            if option != "":
                alternative = Alternative.objects.get(pk=int(option))
                answerOption = AnswerOption()
                answerOption.question = question
                answerOption.response = response
                answerOption.option_choice = alternative
                answerOption.save()
        elif question.type_question == 4:
                try:
                    options = request.POST.getlist("question_"+str(question.pk))
                    for option in options:
                        alternative = Alternative.objects.get(pk=int(option))
                        answerOption = AnswerOption()
                        answerOption.question = question
                        answerOption.response = response
                        answerOption.option_choice = alternative
                        answerOption.save()                    
                except Exception as e:
                    pass
        elif question.type_question == 5:
            answer = Answer()
            answer.question = question
            answer.response = response
            try:
                not_apply = request.POST["not_apply_question_"+str(question.pk)]
                answer.not_apply = True
            except Exception as e:
                answer.scale = request.POST["question_"+str(question.pk)]
            answer.save()
        elif question.type_question == 6:
            try:
                answer = Answer()
                answer.question = question
                answer.response = response

                resp = request.POST["question_"+str(question.pk)]
 
                if resp == "not_apply":
                    answer.dont_apply = True
                else:
                    answer.yes_no = int(resp)  
                
                answer.save()
            except Exception as e:
                pass

    return render(request, 'form/finish_form_response.html')

#@transaction.atomic
@login_required
def form_save(request):
    if not request.is_ajax():
        raise Http404

    title = request.POST["title"]
    description = request.POST["description"]    
    questions = json.loads(request.POST["questions"])

    form = Form.objects.create(
        title=title,
        description=description
        )

    for item in questions:
        
        question = Question.objects.create(
            title=item["question"],
            description=item["description"],
            form=form,
            type_question=item["type"],
            is_required=item["is_required"],
            max_size=item["max_characters"],
            max_scale=item["max_rating"],
            show_yes_no=item["show_yes_no"],
            left_label=item["label_left"],
            middle_label=item["label_middle"],
            right_label=item["label_right"]
            )

        if question.type_question == 3 or question.type_question == 4:
            for alternative in item["choices"].split("\n"):
                if alternative != "":
                    alternative = Alternative.objects.create(
                        title=alternative,
                        question=question
                        )
                
    response_data = {}
    response_data['result'] = 'success'
    response_data['message'] = 'O formulário foi cadastrado com sucesso!'
    response_data['pk'] = form.pk

    return JsonResponse(response_data)

eajforms/forms/templates/form/finish_form_response.html
{% load static %}
<!doctype html>
<html lang="pt-br">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
  <link rel="icon" type="image/png" sizes="96x96" href="{% static 'assets/img/favicon.png' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

  <title>EAJ Forms - Responder Formulário
    {% block title-page %}
    {% endblock %}
  </title>

  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
  <meta name="viewport" content="width=device-width" />

  <!-- Bootstrap core CSS     -->
  <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" />

  <link href="{% static 'assets/css/utilities.css' %}" rel="stylesheet">

  <!--  Paper Dashboard core CSS    -->
  <link href="{% static 'assets/css/paper-dashboard.css' %}" rel="stylesheet" />

  <!--  Fonts and icons     -->
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
  <link href="{% static 'assets/css/themify-icons.css' %}" rel="stylesheet">

  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/9.8.1/css/bootstrap-slider.min.css">

  <style>

    .help-block{
      margin-bottom: 30px;
    }
    label.label-option{
      font-weight: initial;
    }
  </style>

</head>
<body>
  <div id="app">
    <div class="main-panel" style="height: 100vh; !important; float: initial; width: initial;">
      <div class="content">
        <div class="container-fluid">
          <br/><br/>
          <div class="row">
            <div class="col-md-8 col-md-offset-2">
              <div class="card">
                <div class="content text-center">
                  <img style="width: 15%;" src="{% static 'assets/img/success.svg' %}" alt="success">
                  <h3>Muito obrigado!</h3>
                  <h5>Sua opinião é muito importante para nós,
                    <br/>obrigado por nos enviar.</h5>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <footer class="footer" style="position: absolute;">
          <div class="container-fluid">
            <nav class="pull-left">
              <ul>
              </ul>
            </nav>
            <div class="copyright pull-right">
              &copy; 2017, desenvolvido por <a href="#">EAJ Forms</a>
            </div>
          </div>
        </footer>
      </div>
    </div>

    <!--   Core JS Files. Extra: PerfectScrollbar + TouchPunch libraries inside jquery-ui.min.js   -->
    <script src="{% static 'assets/js/jquery-1.10.2.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/js/jquery-ui.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}" type="text/javascript"></script>

    <!-- Paper Dashboard PRO Core javascript and methods for Demo purpose -->
    <script src="{% static 'assets/js/paper-dashboard.js' %}"></script>

    <script>
      function close(){
        window.close();
      }
    </script>
  </body>
  </html>

eajforms/forms/templates/form/form_reply.html
{% extends "base.html" %}

{% block title-page %}
Responder Formulário
{% endblock %}

eajforms/forms/templates/form/form_response.html
{% load static %}
<!doctype html>
<html lang="pt-br">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
  <link rel="icon" type="image/png" sizes="96x96" href="{% static 'assets/img/favicon.png' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

  <title>EAJ Forms - Responder Formulário
    {% block title-page %}
    {% endblock %}
  </title>

  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
  <meta name="viewport" content="width=device-width" />

  <!-- Bootstrap core CSS     -->
  <link href="{% static 'assets/css/bootstrap.min.css' %}" rel="stylesheet" />

  <link href="{% static 'assets/css/utilities.css' %}" rel="stylesheet">

  <!--  Paper Dashboard core CSS    -->
  <link href="{% static 'assets/css/paper-dashboard.css' %}" rel="stylesheet" />

  <!--  Fonts and icons     -->
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
  <link href="{% static 'assets/css/themify-icons.css' %}" rel="stylesheet">

  <link rel="stylesheet" type="text/css" href="{% static 'assets/css/bootstrap-slider.min.css' %}">

  <style>
    .main-panel{
      height: 100vh; !important;
    }
    .help-block{
      margin-bottom: 30px;
    }
    label.label-option{
      font-weight: initial;
    }
  </style>

</head>
<body>
  <div id="app">
    <div class="wrapper">
      <div class="main-panel" style="height: 100vh; !important; float: initial; width: initial;">
        <div class="content">
          <div class="container-fluid">
            <div class="row">
             <div class="col-md-8 col-md-offset-2">
              <h4 class="title text-center">{{form.title|lower|capfirst}}</h4>
              <p class="category" style="text-align: justify;" >{{form.description}}</p><br/>
              <div class="card">
                <div class="content">
                  <form action="{% url 'form_response_save' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" value="{{form.pk}}" name="form_id">
                    <input type="hidden" value="{{apply_form.access_code}}" name="apply_form_access_code">
                    {% for question in form.question_set.all %}
                    {% if question.type_question == 1 %}
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label>{{ forloop.counter }} - {{question.title|lower|capfirst}}{{ question.is_required|yesno:"*," }} </label>
                          <input {{ question.is_required|yesno:"required," }} 
                          {% if question.max_size != 0 %}
                          maxlength="{{question.max_size}}" 
                          {% endif %}
                          type="text" 
                          class="form-control"
                          name="question_{{question.pk}}">
                          <span class="help-block">{{question.description|lower|capfirst}}</span>
                        </div>
                      </div>
                    </div>
                    {% elif question.type_question == 2 %}
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label>{{ forloop.counter }} - {{question.title|lower|capfirst}}{{ question.is_required|yesno:"*," }}</label>
                          <textarea {{ question.is_required|yesno:"required," }} 
                          class="form-control"
                          {% if question.max_size != 0 %}
                          maxlength="{{question.max_size}}" 
                          {% endif %}
                          name="question_{{question.pk}}"></textarea>
                          <span class="help-block">{{question.description|lower|capfirst}}</span>
                        </div>
                      </div>
                    </div>
                    {% elif question.type_question == 3 %}
                    <div class="row">
                      <div class="col-md-12">
                        <div class="form-group">
                          <label>{{ forloop.counter }} - {{question.title|lower|capfirst}}{{ question.is_required|yesno:"*," }}</label>
                          <select name="question_{{question.pk}}" {{ question.is_required|yesno:"required," }} name="" id="" class="form-control">
                            <option value="" disabled selected>Selecione uma das opções</option>
                            {% for alternative in question.alternative_set.all  %}
                            <option value="{{alternative.pk}}">{{alternative.title}}</option>
                            {% endfor %}
                          </select>
                          <span class="help-block">{{question.description|lower|capfirst}}</span>
                        </div>
                      </div>
                    </div>
                    {% elif question.type_question == 4 %}       
                    <label>{{ forloop.counter }} - {{question.title|lower|capfirst}}{{ question.is_required|yesno:"*," }}</label>
                    <div class="row">
                      {% for alternative in question.alternative_set.all  %}
                      <div class="{% if forloop.counter|divisibleby:2 %}col-md-8{%else%}col-md-4{% endif %}">
                        <div class="" style="margin-top: initial;" >
                         <input id="question_{{question.pk}}_alternative_{{alternative.pk}}" name="question_{{question.pk}}" type="checkbox" class="" value="{{alternative.pk}}">
                         <label class="label-option" for="question_{{question.pk}}_alternative_{{alternative.pk}}">
                          {{alternative.title|lower|capfirst}}
                        </label>
                      </div>
                    </div>
                    {% endfor %}
                  </div>
                  <span class="help-block">{{question.description|lower|capfirst}}</span>
                  {% elif question.type_question == 5 %}
                  <div class="row">
                    <div class="col-md-12">
                      <div class="form-group">
                        <label>{{ forloop.counter }} - {{question.title|lower|capfirst}} {{ question.is_required|yesno:"*," }}</label><br/>
                        <input {{ question.is_required|yesno:"required," }} style="width:100%; margin: 0 auto;"
                        type="text"
                        name="question_{{question.pk}}"
                        data-provide="slider"
                        data-slider-min="1"
                        data-slider-max="{{question.max_scale}}"
                        data-slider-step="1"
                        data-slider-value="1"
                        >
                        <div class="row">
                          <div class="col-md-4 text-left">
                            {{question.left_label|lower|capfirst}}
                          </div>
                          <div class="col-md-4 text-center">
                            {{question.middle_label|lower|capfirst}}
                          </div>
                          <div class="col-md-4 text-right">
                            {{question.right_label|lower|capfirst}}
                          </div>
                        </div>
                        <div class="row">
                          <div class="col-md-12">
                            <div class="" style="margin-top: initial;">
                              <input id="not_apply_question_{{question.pk}}" name="not_apply_question_{{question.pk}}" type="checkbox" class="" value="1">
                              <label class="label-option" for="not_apply_question_{{question.pk}}">
                                Não se aplica (Não precisei de nenhum desses serviços)
                              </label>
                            </div>
                          </div>
                        </div>
                        <span class="help-block">{{question.description|lower|capfirst}}</span>
                      </div>
                    </div>
                  </div>
                  {% elif question.type_question == 6 %}
                  <label>{{ forloop.counter }} - {{question.title|lower|capfirst}}{{ question.is_required|yesno:"*," }}</label>
                  <div class="row">
                    <div class="col-md-12">
                      <div class="" style="margin-top: initial;">
                        <input {{ question.is_required|yesno:"required," }} id="yes_question_{{question.pk}}" name="question_{{question.pk}}" type="radio" class="" value="1">
                        <label class="label-option" for="yes_question_{{question.pk}}">
                         {{ question.show_yes_no|yesno:"Sim,Concordo" }}
                       </label>
                     </div>
                   </div>
                   <div class="col-md-12">
                    <div class="" style="margin-top: initial;">
                      <input id="yesno_question_{{question.pk}}" name="question_{{question.pk}}" type="radio" class="" value="2">
                      <label class="label-option" for="yesno_question_{{question.pk}}">
                        {{ question.show_yes_no|yesno:"Parcialmente,Concordo parcialmente" }}
                      </label>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <div class="" style="margin-top: initial;">
                    <input id="no_question_{{question.pk}}" name="question_{{question.pk}}" type="radio" class="" value="3">
                    <label class="label-option" for="no_question_{{question.pk}}">
                        {{ question.show_yes_no|yesno:"Não,Discordo" }}
                      </label>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <div class="" style="margin-top: initial;">
                      <input name="question_{{question.pk}}" id="not_apply_question_{{question.pk}}" type="radio" class="" value="not_apply">
                      <label class="label-option" for="not_apply_question_{{question.pk}}">
                        Não se aplica (Não precisei de nenhum desses serviços)
                      </label>
                    </div>
                  </div>
                </div>
                <span class="help-block">{{question.description|lower|capfirst}}</span>
                {% endif %}
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8 col-md-offset-2 text-center">
          <button class="btn btn-success btn-lg btn-fill btn-wd">
            <span class="btn-label">
              <i class="fa fa-save"></i>
            </span> Enviar Respostas
          </button>
        </div>
      </div>
    </div>
  </form>
  <footer class="footer">
    <div class="container-fluid">
      <nav class="pull-left">
        <ul>
        </ul>
      </nav>
      <div class="copyright pull-right">
        &copy; 2017, desenvolvido por <a href="#">EAJ Forms</a>
      </div>
    </div>
  </footer>
</div>
</div>
</div>

<!--   Core JS Files. Extra: PerfectScrollbar + TouchPunch libraries inside jquery-ui.min.js   -->
<script src="{% static 'assets/js/jquery-1.10.2.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/jquery-ui.min.js' %}" type="text/javascript"></script>
<script src="{% static 'assets/js/bootstrap.min.js' %}" type="text/javascript"></script>

<!--  Forms Validations Plugin -->
<script src="{% static 'assets/js/jquery.validate.min.js' %}"></script>

<!--  Select Picker Plugin -->
<script src="{% static 'assets/js/bootstrap-selectpicker.js' %}"></script>

<!--  Checkbox, Radio, Switch and Tags Input Plugins -->
<script src="{% static 'assets/js/bootstrap-checkbox-radio-switch-tags.js' %}"></script>

<!-- Paper Dashboard PRO Core javascript and methods for Demo purpose -->
<script src="{% static 'assets/js/paper-dashboard.js' %}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/9.8.1/bootstrap-slider.min.js"></script>

</body>
</html>