eajforms/core/urls.py
from django.conf.urls import url
from . import views as core_views

urlpatterns = [
    url(r'^class/list/$', core_views.class_list, name='class_list'),
    url(r'^class/(?P<pk>\d+)/matriculations/$', core_views.class_matriculations, name='class_matriculations'),
    url(r'^class/matriculation/upload$', core_views.class_matriculation_upload, name='class_matriculation_upload'),

    url(r'^docente/list/$', core_views.docente_list, name='docente_list'),
    url(r'^docente/upload/$', core_views.docente_upload, name='docente_upload'),

    url(r'^course/list/$', core_views.course_list, name='course_list'),

    url(r'^avaluated/load/$', core_views.load_avaluated_by_type, name='load_avaluated_by_type'),
]

eajforms/urls.py
from django.conf.urls import include, url
from django.contrib.auth.views import login, logout
from django.contrib import admin
from eajforms.core import views as core_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', core_views.dashboard, name='home'),
    url(r'^accounts/login/$', login, name='login', kwargs={'redirect_authenticated_user': True}),
    url(r'^accounts/logout/$', logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^dashboard/$', core_views.dashboard, name='dashboard'),
    url(r'', include('eajforms.forms.urls')),
    url(r'', include('eajforms.core.urls'))
]

eajforms/core/models.py
from django.db import models
from django.contrib.auth.models import User


class Person(User):
    cpf = models.CharField(max_length=20, null=True, unique=True)
    full_name = models.CharField(max_length=100)

    class Meta:
        verbose_name = "Pessoa"
        verbose_name_plural = "Pessoas"

    def __str__(self):
        return self.full_name


class Docente(Person):
    
    class Meta:
        verbose_name = "docente"
        verbose_name_plural = "docentes"

    def __str__(self):
        return self.full_name


class DocenteCoursePole(models.Model):
    course_pole = models.ForeignKey('CoursePole')
    docente = models.ForeignKey('Docente')
    create_at = models.DateField(auto_now_add=True)
    STATUS_CHOICES = (
        (1, "Ativado"),
        (2, "Desativado")
        )
    status = models.PositiveIntegerField(choices=STATUS_CHOICES)
    TEACHER = 1
    SEARCH_TEACHER = 2
    MEDIATOR_TEACHER = 3
    TUTOR = 4
    DISTANCE_TUTOR = 5
    TYPE_DOCENTE_CHOICE = (
        (TEACHER, "Professor"),
        (SEARCH_TEACHER, "Professor Pesquisador"),
        (MEDIATOR_TEACHER, "Professor Mediador"),
        (TUTOR, "Tutor Presencial"),
        (DISTANCE_TUTOR, "Tutor EAD"),

    )
    type_docente = models.PositiveIntegerField(choices=TYPE_DOCENTE_CHOICE, default=1)

    class Meta:
        verbose_name = "Docente em um curso"
        verbose_name_plural = "Docentes em um curso"

    def __str__(self):
        return self.docente.full_name


class Pole(models.Model):
    name = models.CharField(max_length=50)
    
    class Meta:
        verbose_name = "Polo"
        verbose_name_plural = "Polos"

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name = "Curso"
        verbose_name_plural = "Cursos"

    def __str__(self):
        return self.name


class ClassCourse(models.Model):
    name = models.CharField("nome da turma", max_length=100)
    course_pole = models.ForeignKey("CoursePole")
    start_at = models.DateField(auto_now=False, auto_now_add=False)
    end_at = models.DateField(auto_now=False, auto_now_add=False)

    class Meta:
        verbose_name = "Turma"
        verbose_name_plural = "Turmas"

    def __str__(self):
        return self.course_pole.course.name + " - " + str(self.start_at)


class Matriculation(models.Model):
    class_course = models.ForeignKey('ClassCourse')
    student = models.ForeignKey('Student')
    matriculation = models.CharField(max_length=30, null=True, blank=True)
    REGISTERED = 1
    RETIRED = 2
    LOCKED = 3
    FINISHED = 4
    SITUATION_CHOICES = (
        (REGISTERED, "Matriculado"),
        (RETIRED, "Jubilado"),
        (LOCKED, "Trancado"),
        (FINISHED, "Finalizado")
        )
    situation = models.PositiveIntegerField('Situação da Matrícula', choices=SITUATION_CHOICES, default=1)

    class Meta:
        verbose_name = "Matrícula"
        verbose_name_plural = "Matrículas"

    def __str__(self):
        return self.student.full_name + " - " + str(self.situation)

class Student(Person):
    is_egress = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Aluno"
        verbose_name_plural = "Alunos"

    def __str__(self):
        return self.full_name


class CoursePole(models.Model):
    course = models.ForeignKey(Course)
    pole = models.ForeignKey(Pole)

    class Meta:
        verbose_name = "Curso do Polo"
        verbose_name_plural = "Cursos do Polo"

    def __str__(self):
        return self.course.name + " - " + self.pole.name


class CoordinatorCourse(models.Model):
    course = models.ForeignKey(Course)
    docente = models.ForeignKey(Docente, null=True, default=None)
    STATUS_CHOICES = (
        (1, "Ativado"),
        (2, "Desativado")
        )
    status = models.PositiveIntegerField(choices=STATUS_CHOICES)
    create_at = models.DateField("Data de criação", auto_now=True)

    class Meta:
        verbose_name = "Coordenador de Curso"
        verbose_name_plural = "Coordenadores de Curso"

    def __str__(self):
        return self.docente.full_name + " - " + self.course.name


class CoordinatorPole(models.Model):
    pole = models.ForeignKey(Pole)
    docente = models.ForeignKey(Docente, null=True, default=None)
    STATUS_CHOICES = (
        (1, "Ativado"),
        (2, "Desativado")
        )
    status = models.PositiveIntegerField(choices=STATUS_CHOICES)
    create_at = models.DateField("Data de criação", auto_now=True)

    class Meta:
        verbose_name = "Coordenador de Polo"
        verbose_name_plural = "Coordenadores de Polo"

    def __str__(self):
        return self.pole.name + " - "+ self.docente.full_name

eajforms/core/forms.py
from django import forms

class MatriculationsUploadFileForm(forms.Form):
    file = forms.FileField(
        label='Arquivo para importação',
        widget=forms.FileInput(attrs={
            'class': 'form-control',
            'data-multiple-caption': '{count} files selected'
        })
    )


class DocentesUploadFileForm(forms.Form):
    file = forms.FileField(
        label='Arquivo para importação',
        widget=forms.FileInput(attrs={
            'class': 'form-control',
            'data-multiple-caption': '{count} files selected'
        })
    )

eajforms/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import MatriculationsUploadFileForm, DocentesUploadFileForm
import json, csv, os, random
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.db import transaction
from .models import ClassCourse, Student, Matriculation, Docente, Course, \
                    CoordinatorPole, CoordinatorCourse, DocenteCoursePole, Pole, Course
from django.http import JsonResponse, Http404
from django.core import serializers


def home(request):
    return render(request, 'index.html')


def login(request):
    return render(request, 'login.html')


@login_required
def dashboard(request):
    return render(request, 'dashboard.html')

@login_required
def class_list(request):
    class_list = ClassCourse.objects.all()

    paginator = Paginator(class_list, 10)

    page = request.GET.get('page')
    try:
        class_list = paginator.page(page)
    except PageNotAnInteger:
        class_list = paginator.page(1)
    except EmptyPage:
        class_list = paginator.page(paginator.num_pages)

    return render(request, 'class/class_list.html', {"class_list":class_list})


@login_required
def course_list(request):
    course_list = Course.objects.all()

    paginator = Paginator(course_list, 10)

    page = request.GET.get('page')
    try:
        course_list = paginator.page(page)
    except PageNotAnInteger:
        course_list = paginator.page(1)
    except EmptyPage:
        course_list = paginator.page(paginator.num_pages)

    return render(request, 'course/course_list.html', {"course_list":course_list})


@login_required
def docente_list(request):
    form = DocentesUploadFileForm()

    docente_list = Docente.objects.all()

    paginator = Paginator(docente_list, 10)

    page = request.GET.get('page')
    try:
        docente_list = paginator.page(page)
    except PageNotAnInteger:
        docente_list = paginator.page(1)
    except EmptyPage:
        docente_list = paginator.page(paginator.num_pages)

    return render(request, 'docente/docente_list.html', {"docente_list":docente_list, "form":form})

@login_required
@transaction.atomic
def docente_upload(request):
    if request.method == "POST":
        form = DocentesUploadFileForm(request.POST, request.FILES)
            
        if form.is_valid():
            filehandle = request.FILES['file']
            fs = FileSystemStorage()
            filename = fs.save(filehandle.name, filehandle)
            uploaded_file_url = fs.url(filename)

            with open(settings.BASE_DIR + "/" + uploaded_file_url, 'r') as csvfile:
                reader = csv.DictReader(csvfile)
                for row in reader:
                    name = row["NOME"].strip()
                    first_name = row["NOME"].strip().split(" ")[0]
                    cpf = row["CPF"].strip()
                    email = row["EMAIL"].strip()

                    docente = Docente.objects.filter(cpf=cpf)

                    if not docente:
                        docente = Docente.objects.create(
                            full_name=name,
                            username=first_name+str(random.randint(9, 99999)),
                            cpf=cpf,
                            email=email
                            )

        _delete_file(settings.BASE_DIR + "/" + uploaded_file_url)

        return redirect('docente_list')


@login_required
def class_matriculations(request, pk):
    form = MatriculationsUploadFileForm()
    class_ = ClassCourse.objects.get(pk=pk)
    return render(request, 'class/class_matriculations.html', {"class":class_, "form":form})

@login_required
@transaction.atomic
def class_matriculation_upload(request):
    if request.method == "POST":
        form = MatriculationsUploadFileForm(request.POST, request.FILES)
            
        if form.is_valid():
            filehandle = request.FILES['file']
            fs = FileSystemStorage()
            filename = fs.save(filehandle.name, filehandle)
            uploaded_file_url = fs.url(filename)

            class_course = ClassCourse.objects.get(pk=int(request.POST['class_course_id']))

            with open(settings.BASE_DIR + "/" + uploaded_file_url, 'r') as csvfile:
                reader = csv.DictReader(csvfile)
                for row in reader:
                    name = row["NOME"].strip()
                    first_name = row["NOME"].strip().split(" ")[0]
                    cpf = row["CPF"].strip()
                    email = row["EMAIL"].strip()

                    student = Student.objects.filter(cpf=cpf)

                    if not student:
                        student = Student.objects.create(
                            full_name=name,
                            username=first_name+str(random.randint(9, 99999)),
                            cpf=cpf,
                            email=email
                            )
                    else:
                        student = student[0]

                    matriculation = Matriculation.objects.filter(student=student, class_course=class_course)

                    if not matriculation:
                        matriculation = Matriculation.objects.create(
                            student=student,
                            class_course=class_course
                            )
                    else:
                        matriculation[0].situation = 1
                        matriculation[0].save()
        else:
            pass

        _delete_file(settings.BASE_DIR + "/" + uploaded_file_url)

        class_ = ClassCourse.objects.get(pk=int(request.POST['class_course_id']))
        return render(request, 'class/class_matriculations.html', {"class":class_, "form":form})


@login_required
def _delete_file(path):
    if os.path.isfile(path):
        os.remove(path)


@login_required
def load_avaluated_by_type(request):
    if not request.is_ajax():
        raise Http404

    type_evaluated = int(request.POST['type'])

    list_data = []

    if type_evaluated == 1:
        coordinators_pole = CoordinatorPole.objects.filter(status=1)
        for cp in coordinators_pole:
            list_data.append({
                "value":cp.pk,
                "display":cp.pole.name + " - " + cp.docente.full_name
            })
    elif type_evaluated == 2:
        coordinators_course = CoordinatorCourse.objects.filter(status=1)
        for cc in coordinators_course:
            list_data.append({
                "value":cc.pk,
                "display":cc.course.name + " - " + cc.docente.full_name
            })
    elif type_evaluated == 3 or type_evaluated == 4 or type_evaluated == 5 or type_evaluated == 6 or type_evaluated == 7:
        docente_course_pole = DocenteCoursePole.objects.filter(status=1, type_docente=type_evaluated-2)
        for dcp in docente_course_pole:
            list_data.append({
                "value":dcp.pk,
                "display":dcp.course_pole.pole.name + " | " + dcp.course_pole.course.name + " - " + dcp.docente.full_name
            })
    elif type_evaluated == 8:
        course_list = Course.objects.all()
        for c in course_list:
            list_data.append({
                "value":c.pk,
                "display":c.name
            })
    elif type_evaluated == 9:
        pole_list = Pole.objects.all()
        for p in pole_list:
            list_data.append({
                "value":p.pk,
                "display":p.name
            })

    return JsonResponse(list_data, safe=False)

eajforms/core/templates/class/class_list.html
{% extends "base.html" %}
{% load static %}

{% block title-page %} Listagem de Turmas {% endblock %}

{% block title-navbar-page %} Todos as Turmas {% endblock %}

{% block extra-css %}
<link href="{% static 'assets/css/sweetalert2.min.css' %}" rel="stylesheet">
<style>
    .btn-arrow{
        padding:0px !important;
    }
    input[type="checkbox"]{
        width: 18px !important;
        height: 18px !important;
    }
    .btn-action{
        font-size: 16px;
    }
</style>
{% endblock %}

{% block content %}
<div class="row">
 <div class="col-md-12">
    <div class="card">
      <div class="content">
         <table class="table">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Curso</th>
                    <th>Polo</th>
                    <th class="text-center">Matriculados</th>
                    <th class="text-center">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for class in class_list reversed %}
                <tr>
                    <td>{{class.name}}</td>
                    <td>
                        {{class.course_pole.course.name}}
                        <p class="category">de {{class.start_at|date:"d/m/Y"}} até {{class.end_at|date:"d/m/Y"}}</p>
                    </td>
                    <td>{{class.course_pole.pole.name}}</td>
                    <td class="text-center">{{class.matriculation_set.count}}</td>
                    <td class="text-center" style="white-space: nowrap;">
                        <a href="{% url 'class_matriculations' pk=class.pk %}" rel="tooltip" title="" class="btn btn-success btn-simple btn-xs btn-action" data-original-title="Matriculados">
                            <i class="ti-user"></i>
                        </a>
                        <a href="#" rel="tooltip" title="" class="btn btn-primary btn-simple btn-xs btn-action" data-original-title="Editar">
                            <i class="ti-pencil"></i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% include "pagination.html" with objects=class_list %}
    </div>
</div>
</div>
{% endblock %}

{% block extra-modais %}
{% endblock %}

{% block extra-javascript %}
<script src="{% static 'assets/js/sweetalert2.min.js' %}"></script>
{% endblock %}

eajforms/core/templates/class/class_matriculations.html
{% extends "base.html" %}
{% load static %}

{% block title-page %} Listagem de Matriculados {% endblock %}

{% block title-navbar-page %} Matriculados {% endblock %}

{% block extra-css %}
<link href="{% static 'assets/css/sweetalert2.min.css' %}" rel="stylesheet">
<style>
    .btn-arrow{
        padding:0px !important;
    }
    input[type="checkbox"]{
        width: 18px !important;
        height: 18px !important;
    }
    .btn-action{
        font-size: 16px;
    }
    table.table-detail > tbody > tr > th, table.table-detail > tbody > tr > td{
        border-top: 0px !important;
    }
    table.table-detail > tbody > tr > th{

    }
</style>
{% endblock %}

{% block content %}
<div class="row">
   <div class="col-md-12">
    <div class="card">
      <div class="content table-responsive">
          <table class="table table-detail">
            <tbody>
                <tr>
                    <th>Turma</th><td>{{class.name}}</td>
                    <th>Início</th><td colspan="2">{{class.start_at|date:'d/m/Y'}}</td>
                </tr>
                <tr>
                    <th>Curso</th><td>{{class.course_pole.course.name}}</td>
                    <th>Término</th><td  colspan="2">{{class.end_at|date:'d/m/Y'}}</td>
                </tr>
                <tr>
                    <th>Polo</th><td>{{class.course_pole.pole.name}}</td>
                    <th>Matriculados</th>
                    <form action="{% url 'class_matriculation_upload' %}" enctype="multipart/form-data" method="POST">
                        <td>
                            {% csrf_token %}
                            <input type="hidden" name="class_course_id" value="{{class.id}}">
                            {{ form.file }}
                            <p class="category text-danger">{{ form.file.errors }}</p>
                        </td>
                        <td> <input class="btn btn-xs pull-right" type="submit" value="Enviar"></td>
                    </form>
                </tr>
            </tbody>
        </table>
    </div>
</div>
</div>
</div>
<div class="row">
   <div class="col-md-12">
    <div class="card">
        <div class="header">
            <h5 class="title">{{class.matriculation_set.count}} Matriculados</h5>
        </div>
        <div class="content table-responsive">
           <table class="table">
            <thead>
                <tr>
                    <th>Aluno</th>
                    <th>Email</th>
                    <th>Situação</th>
                    <th class="text-center">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for matriculation in class.matriculation_set.all %}
                <tr>
                    <td>{{matriculation.student.full_name|title}}</td>
                    <td>
                        {{matriculation.student.email}}
                    </td>
                    <td>
                        <span class="label 
                        {% if matriculation.situation == 1 %}
                            label-success
                        {% elif matriculation.situation == 2 %}
                            label-danger
                        {% elif matriculation.situation == 3 %}
                            label-warning
                        {% elif matriculation.situation == 4 %}
                            label-primary
                        {% endif %}
                        ">
                            {{matriculation.get_situation_display}}
                        </span>
                    </td>
                    <td class="text-center" style="white-space: nowrap;">

                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
</div>
</div>
{% endblock %}

{% block extra-modais %}
{% endblock %}

{% block extra-javascript %}
<script src="{% static 'assets/js/sweetalert2.min.js' %}"></script>
{% endblock %}