eajforms/forms/urls.py
from django.conf.urls import url
from eajforms.forms import views as forms_views

urlpatterns = [
    url(r'^form/new/$', forms_views.form_new, name='form_new'),
    url(r'^form/save/$', forms_views.form_save, name='form_save'),
    url(r'^form/list/$', forms_views.form_list, name='form_list'),
    url(r'^form/(?P<pk>\d+)/apply/$', forms_views.form_apply, name='form_apply'),
    url(r'^apply_form/(?P<access_code>\w+)/response/$', forms_views.form_response, name='form_response'),
    url(r'^apply_form/response/save/$', forms_views.form_response_save, name='form_response_save'),
    url(r'^apply_form/list/$', forms_views.apply_form_list, name='apply_form_list'),
    url(r'^apply_form/(?P<access_code>\w+)/result/$', forms_views.apply_form_result, name='apply_form_result'),
]

eajforms/urls.py
from django.conf.urls import include, url
from django.contrib.auth.views import login, logout
from django.contrib import admin
from eajforms.core import views as core_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', core_views.dashboard, name='home'),
    url(r'^accounts/login/$', login, name='login', kwargs={'redirect_authenticated_user': True}),
    url(r'^accounts/logout/$', logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^dashboard/$', core_views.dashboard, name='dashboard'),
    url(r'', include('eajforms.forms.urls')),
    url(r'', include('eajforms.core.urls'))
]

eajforms/forms/models.py
from django.db import models
from eajforms.core.models import Person

# Create your models here.
class Form(models.Model):
    title = models.CharField('Título', max_length=100)
    description = models.TextField('Descrição', max_length=255)
    create_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    
    class Meta:
        verbose_name = "Formulário"
        verbose_name_plural = "Formulários"

    def __str__(self):
        return self.title

class Question(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    form = models.ForeignKey(Form)
    SHORT_TEXT = 1
    LONG_TEXT = 2
    UNIQUE_CHOICE = 3
    MULTIPLE_CHOICE = 4
    ESCALE = 5
    AGREE_DISAGREE = 6
    TYPE_QUESTION_CHOICES = (
        (SHORT_TEXT, "Texto Curto"),
        (LONG_TEXT, "Texto Longo"),
        (UNIQUE_CHOICE, "Escolha Única"),
        (MULTIPLE_CHOICE, "Escolha Múltipla"),
        (ESCALE, "Escala"),
        (AGREE_DISAGREE, "Concordo ou Discordo"),

    )
    type_question = models.PositiveIntegerField(choices = TYPE_QUESTION_CHOICES)
    is_required = models.BooleanField(default=True)
    related_alternative = models.ForeignKey('Alternative', null=True, blank=True, related_name='related_alternative')
    max_size = models.PositiveIntegerField('Tamanho máximo da resposta', null=True)
    max_scale = models.PositiveIntegerField('Escala máxima da resposta', null=True)
    show_yes_no = models.BooleanField('Mostrar Sim ou Não', default=False)
    left_label = models.CharField('Label esquerdo', max_length=50)
    middle_label = models.CharField('Label central', max_length=50)
    right_label = models.CharField('Label direito', max_length=50)

    class Meta:
        verbose_name = "Questão"
        verbose_name_plural = "Questões"

    def __str__(self):
        return self.title

class Alternative(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=255, null=True, blank=True)
    question = models.ForeignKey(Question)

    class Meta:
        verbose_name = "Alternativa"
        verbose_name_plural = "Alternativas"

    def __str__(self):
        return self.title


class Response(models.Model):
    person = models.ForeignKey(Person, null=True)
    create_at = models.DateTimeField(auto_now_add=True)
    apply_form = models.ForeignKey("ApplyForm", default=1)
    
    class Meta:
        verbose_name = "Resposta Central"
        verbose_name_plural = "Respostas Central"

    def __str__(self):
        return str(self.create_at)


class Answer(models.Model):
    response = models.ForeignKey(Response, null=True)
    question = models.ForeignKey(Question)
    text = models.CharField(max_length=255, null=True)
    scale = models.PositiveIntegerField(null=True)
    dont_apply = models.BooleanField('Não se aplica', default=False)
    OPTION_CHOICES = (
        (1, "Concordo/Sim"),
        (2, "Concordo parcialmente/Parcialmente"),
        (3, "Discordo/Não"),

    )
    yes_no = models.PositiveIntegerField(choices = OPTION_CHOICES, null=True, blank=True)

    class Meta:
        verbose_name = "Resposta"
        verbose_name_plural = "Respostas"

    def __str__(self):
        return str(self.question.title) + " - " + str(self.text) + "Null"

class AnswerOption(models.Model):
    question = models.ForeignKey(Question)
    response = models.ForeignKey(Response)
    option_choice = models.ForeignKey(Alternative, null=True, blank=True)

    class Meta:
        verbose_name = "Alternativa selecionada"
        verbose_name_plural = "Alternativa selecionada"

    def __str__(self):
        return self.question.title + " / " + self.option_choice.title


class ApplyForm(models.Model):
    form = models.ForeignKey(Form)
    DOCENTE = 1
    COORDINATOR = 2
    COURSE = 3
    POLE = 4
    TYPE_EVALUATED_CHOICE = (
        (DOCENTE,"Docente"),
        (COORDINATOR,"Coordenador"),
        (COURSE, "Curso"),
        (POLE, "Polo")

    )
    type_evaluated = models.PositiveIntegerField('Tipo de Avaliado',choices=TYPE_EVALUATED_CHOICE)
    login_required = models.BooleanField('Login é obrigatório?', default=False)
    create_at = models.DateTimeField(auto_now_add=True)
    access_code = models.CharField('código de acesso', unique=True, max_length=64)
    OPEN = 1
    CLOSE = 2
    STATUS_FORM_CHOICES = (
        (OPEN, "Aberto"),
        (CLOSE, "Fechado"),
    )
    status = models.PositiveIntegerField(choices = STATUS_FORM_CHOICES, default=1)

    class Meta:
        verbose_name = "Formulário Aplicado"
        verbose_name_plural = "Formulários Aplicados"

    def __str__(self):
        return self.form.title

eajforms/forms/admin.py
from django.contrib import admin
from eajforms.forms.models import *

# Register your models here.

class AlternativeInline(admin.TabularInline):
    model = Alternative

class QuestionAdmin(admin.ModelAdmin):
    inlines = [AlternativeInline]

class QuestionInline(admin.TabularInline):
    model = Question

class FormAdmin(admin.ModelAdmin):
    inlines = [QuestionInline]

admin.site.register(Form, FormAdmin)
admin.site.register(Question, QuestionAdmin)
admin.site.register(Alternative)
admin.site.register(Answer)
admin.site.register(AnswerOption)
admin.site.register(Response)
admin.site.register(ApplyForm)

eajforms/forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    name = 'forms'

eajforms/forms/tests.py
from django.test import TestCase

# Create your tests here.

eajforms/forms/utils.py
import hashlib, string, random, datetime

from eajforms.forms.models import ApplyForm

def generate_hash_key(salt, random_str_size=5):
    random_str = random_key(random_str_size)
    text = random_str + salt
    generate_hash = hashlib.sha224(text.encode('utf-8')).hexdigest()
    
    if ApplyForm.objects.filter(access_code=generate_hash).exists():
        return generate_hash_key(salt, random_str_size)

    return generate_hash

eajforms/forms/views.py
import json
from django.shortcuts import render, redirect, get_object_or_404, resolve_url as r
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, Http404
from .models import Form, Question, Alternative, Answer, AnswerOption, Response, ApplyForm
from eajforms.core.models import CoordinatorPole
from django.db import transaction


def reply_form(request, formid):
    return render(request, 'form/form_reply.html')


def form_new(request):
    return render(request, 'form/form_form.html')


def form_list(request):
    forms = Form.objects.all()
    return render(request, 'form/form_list.html', {"forms":forms})


def apply_form_list(request):
    apply_forms = ApplyForm.objects.all()
    return render(request, 'apply_form/apply_form_list.html', {"apply_forms":apply_forms})


def apply_form_result(request, access_code):
    apply_form = get_object_or_404(ApplyForm, access_code=access_code)

    return render(request, 'apply_form/apply_form_result.html', {"apply_form":apply_form})


def form_apply(request, pk):
    form = get_object_or_404(Form, pk=pk)

    coordinators_pole = CoordinatorPole.objects.filter(status=1)

    return render(request, 'form/form_apply.html', {"form":form, "coordinators_pole":coordinators_pole})


def form_response(request, access_code):
    apply_form = get_object_or_404(ApplyForm, access_code=access_code)
    form = apply_form.form

    return render(request, 'form/form_response.html', {"form":form, "apply_form":apply_form})


#@transaction.atomic
def form_response_save(request):
    form = Form.objects.get(pk=request.POST["form_id"])
    response = Response()
    response.apply_form = get_object_or_404(ApplyForm, access_code=request.POST["apply_form_access_code"])
    response.save()

    for question in form.question_set.all():
        
        if question.type_question == 1:
            answer = Answer()
            answer.question = question
            answer.response = response
            answer.text = request.POST["question_"+str(question.pk)]
            answer.save()
        elif question.type_question == 2:
            answer = Answer()
            answer.question = question
            answer.response = response
            answer.text = request.POST["question_"+str(question.pk)]
            answer.save()
        elif question.type_question == 3:
            option = request.POST["question_"+str(question.pk)]
            if option != "":
                alternative = Alternative.objects.get(pk=int(option))
                answerOption = AnswerOption()
                answerOption.question = question
                answerOption.response = response
                answerOption.option_choice = alternative
                answerOption.save()
        elif question.type_question == 4:
                try:
                    options = request.POST.getlist("question_"+str(question.pk))
                    for option in options:
                        alternative = Alternative.objects.get(pk=int(option))
                        answerOption = AnswerOption()
                        answerOption.question = question
                        answerOption.response = response
                        answerOption.option_choice = alternative
                        answerOption.save()                    
                except Exception as e:
                    pass
        elif question.type_question == 5:
            answer = Answer()
            answer.question = question
            answer.response = response
            try:
                not_apply = request.POST["not_apply_question_"+str(question.pk)]
                answer.not_apply = True
            except Exception as e:
                answer.scale = request.POST["question_"+str(question.pk)]
            answer.save()
        elif question.type_question == 6:
            try:
                answer = Answer()
                answer.question = question
                answer.response = response

                resp = request.POST["question_"+str(question.pk)]
 
                if resp == "not_apply":
                    answer.dont_apply = True
                else:
                    answer.yes_no = int(resp)  
                
                answer.save()
            except Exception as e:
                pass

    return render(request, 'form/finish_form_response.html')

#@transaction.atomic
@login_required
def form_save(request):
    if not request.is_ajax():
        raise Http404

    title = request.POST["title"]
    description = request.POST["description"]    
    questions = json.loads(request.POST["questions"])

    form = Form.objects.create(
        title=title,
        description=description
        )

    for item in questions:
        
        question = Question.objects.create(
            title=item["question"],
            description=item["description"],
            form=form,
            type_question=item["type"],
            is_required=item["is_required"],
            max_size=item["max_characters"],
            max_scale=item["max_rating"],
            show_yes_no=item["show_yes_no"],
            left_label=item["label_left"],
            middle_label=item["label_middle"],
            right_label=item["label_right"]
            )

        if question.type_question == 3 or question.type_question == 4:
            for alternative in item["choices"].split("\n"):
                if alternative != "":
                    alternative = Alternative.objects.create(
                        title=alternative,
                        question=question
                        )
                
    response_data = {}
    response_data['result'] = 'success'
    response_data['message'] = 'O formulário foi cadastrado com sucesso!'
    response_data['pk'] = form.pk

    return JsonResponse(response_data)

eajforms/forms/templates/apply_form/apply_form_list.html
{% extends "base.html" %}
{% load static %}

{% block title-page %} Listagem dos Formulários Aplicados {% endblock %}

{% block title-navbar-page %} Formulários Aplicados {% endblock %}

{% block extra-css %}
<link href="{% static 'assets/css/sweetalert2.min.css' %}" rel="stylesheet">
<style>
    .btn-arrow{
        padding:0px !important;
    }
    input[type="checkbox"]{
        width: 18px !important;
        height: 18px !important;
    }
    .btn-action{
        font-size: 16px;
    }
</style>
{% endblock %}

{% block content %}
<div class="row">
 <div class="col-md-12">
    <div class="card">
      <div class="content table-responsive">
         <table class="table">
            <thead>
                <tr>
                    <th style="width:40%;">Formulário</th>
                    <th>Avaliado</th>
                    <th class="text-center">Situação</th>
                    <th class="text-center">Total de Respostas</th>
                    <th class="text-center">Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for apply_form in apply_forms reversed %}
                <tr>
                    <td>
                        <span><strong>{{apply_form.form.title}}</strong> </span><br/>
                        <p class="category" style="text-align:justify;">{{apply_form.form.description|truncatechars:85}}</p>
                    </td>
                    <td>
                        <span><strong>Agronomia</strong> </span><br/>
                        <p class="category" style="text-align:justify;">
                            {{apply_form.get_type_evaluated_display}}
                        </p>
                    </td>
                    <td class="text-center">
                    {% if apply_form.status == 1 %}
                        <span class="label label-success">Aberto</span>
                    {% else %}
                        <span class="label label-danger">Finalizado</span>
                    {% endif  %}
                    </td>
                    <td class="text-center">
                        {{ apply_form.response_set.count }}
                    </td>
                    <td class="text-center" style="white-space: nowrap;">
                       
                        <a href="{% url 'apply_form_result' access_code=apply_form.access_code %}" rel="tooltip" title="" class="btn btn-success btn-simple btn-xs btn-action" data-original-title="Respostas">
                            <i class="ti-eye"></i>
                        </a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td>
                        <p>Nenhum formulário aplicado até o momento!
                        </p>
                    </td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
</div>
</div>
{% endblock %}

{% block extra-modais %}
{% endblock %}

{% block extra-javascript %}
<script src="{% static 'assets/js/sweetalert2.min.js' %}"></script>
{% endblock %}

eajforms/forms/templates/apply_form/apply_form_result.html
{% extends "base.html" %}
{% load static %}

{% block title-page %} Resultados {% endblock %}

{% block title-navbar-page %} Resultados {% endblock %}

{% block extra-css %}
<link href="{% static 'assets/css/sweetalert2.min.css' %}" rel="stylesheet">
<style>
    .btn-arrow{
        padding:0px !important;
    }
    input[type="checkbox"]{
        width: 18px !important;
        height: 18px !important;
    }

    .btn-action{
        font-size: 16px;
    }
</style>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-6 col-sm-12">
        <div class="card">
            <div class="card-content">

            </div>
            <div class="card-footer">
                <hr>
                <div class="stats">
                    <i class="ti-reload"></i> Updated now
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-sm-6">
        <div class="card">
            <div class="card-content">

            </div>
            <div class="card-footer">
                <hr>
                <div class="stats">
                    <i class="ti-timer"></i> In the last hour
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-sm-6">
        <div class="card">
            <div class="card-content">

            </div>
            <div class="card-footer">
                <hr>
                <div class="stats">
                    <i class="ti-reload"></i> Updated now
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-content">
                <div class="row">
                    <div class="col-md-6">     

                    </div>
                    <div class="col-md-4">     
                     <canvas id="chartjs-4" class="chartjs" width="100" height="100"></canvas>
                 </div>
             </div>
         </div>
     </div>

 </div>
</div>

{% endblock %}

{% block extra-modais %}
{% endblock %}

{% block extra-javascript %}
<script src="{% static 'assets/js/sweetalert2.min.js' %}"></script>
<script src="{% static 'assets/js/Chart.js' %}"></script>


<script>
    ctx = new Chart(document.getElementById("chartjs-4"),
    {
        "type":"pie",
        "data":{
            "labels":["Red","Blue","Yellow"],
            "datasets":[{

                "data":[300,50,100],
                "backgroundColor":["rgb(255, 99, 132)","rgb(54, 162, 235)","rgb(255, 205, 86)"]
            }]
        },
        "options":{
            legend:{
                position:"right",
                verticalAlign: 'center' 
            },
            tooltips: {
              callbacks: {
                label: function(tooltipItem, data) {

                  var dataset = data.datasets[tooltipItem.datasetIndex];

                  var total = dataset.data.reduce(function(previousValue, currentValue, currentIndex, array) {
                    return previousValue + currentValue;
                });

                  var currentValue = dataset.data[tooltipItem.index];

                  var precentage = Math.floor(((currentValue/total) * 100)+0.5);

                  return " "+currentValue+" | "+precentage + "%";
              }
          }
      } 
  }
});


    
</script>

{% endblock %}